### ISSUE TITLE
Typo in partialUpdate

### ISSUE THREAD

**Issue by davidzovko** [e-radionicacom/Inkplate-Arduino-library#101]
In `partialUpdate` function, there is typo at liveOn. I guess it should be leaveOn:
`void Inkplate::partialUpdate(bool _forced, bool liveOn)`

**Comment by nitko12** [comment]
Fixed here:

https://github.com/e-radionicacom/Inkplate-Arduino-library/commit/0912712ccab953a4f347920a1fcc7805aeb1e115
