### ISSUE TITLE
Random reboot loop on start

### ISSUE THREAD

**Issue by brianmay** [e-radionicacom/Inkplate-Arduino-library#105]
On my inkplate10 of the time it works, but sometimes on wakeup or turn on it gets into this reboot loop. From logs:

```
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x32 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
Starting.
Configuring display.
Drawing welcome screen.
Going to sleep.
Starting network stuff.
Setting wifi mode...
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x32 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
Starting.
Configuring display.
Drawing welcome screen.
Going to sleep.
Starting network stuff.
Setting wifi mode...
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x32 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
Starting.
Configuring display.
Drawing welcome screen.
Going to sleep.
Starting network stuff.
Setting wifi mode...
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x32 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
Starting.
Configuring display.
Drawing welcome screen.
Going to sleep.
Starting network stuff.
Setting wifi mode...
[etc]
```

Eventually it works, without making any changes to the code or uploading anything.

Most of the time it reboots in a call to `WiFi.mode()`:

```
    Serial.println(F("Setting wifi mode..."));
    WiFi.mode(WIFI_STA);

    Serial.println(F("Starting wifi network..."));
```

Sometimes however I have observed it rebooting in this code (it prints the first line to Serial, but not the next one):

```
    if (refreshes == 0)
    {
        // Welcome screen
        Serial.println("Drawing welcome screen.");
        display.setCursor(5, 230);
        display.setTextSize(2);
        display.println(F("Welcome to Inkplate 10 Google Calendar!"));
        display.setCursor(5, 250);
        display.println(F("Connecting to WiFi..."));
        display.display();
    }

    Serial.println("Going to sleep.");
```

No idea if this is a hardware issue or a software issue. But based on the fact it randomly works with the same software, I suspect hardware. Hmmm. Wonder if temperature related. Is relatively code right now. Might try to move to a warmer environment, see if that helps.

Code is my version of the Google Calendar example with lots of improvements. And lots of serial debug messages in startup to debug this issue. Requires platformio. https://github.com/brianmay/Google_Calendar

**Comment by BornaBiro** [comment]
Can you please tell me if you are powering Inkplate from the battery or from the USB?
Is there anything else connected to the Inkplate board (some sensors, LEDs,..)?
WiFi has a tendency to draw a lot of current in a short amount of time (current spikes) that can cause reset IC to reset the whole Inkplate board if the battery is weak (cannot supply enough current) or if the USB cable is bad.

**Comment by brianmay** [comment]
Oops. Just realised I had been testing the same cable every time. Will retest with a different cable.

**Comment by brianmay** [comment]
Seems to be OK now. Will mark this as closed until I can reproduce.

Thanks!
