### ISSUE TITLE
Getting WL_NO_SSID_AVAIL, WL_DISCONNECTED

### ISSUE THREAD

**Issue by bicubic** [e-radionicacom/Inkplate-Arduino-library#107]
Hiya. 

I have two inkplate 10's.  Was prototyping on one of them to connect to wifi and display a remotely hosted image. All was going well until it stopped being able to connect to wifi entirely. The exact same sketch works fine on the second inkplate. I am hardcoding wifi credentials in the sketch. 

I put in some debug logs and see the following:
```
4:55:15.487 -> init
14:55:15.487 -> WL_NO_SSID_AVAIL1
14:55:15.487 -> WL_SCAN_COMPLETED2
14:55:15.520 -> WL_CONNECT_FAILED4
14:55:15.520 -> WL_CONNECTION_LOST5
14:55:15.520 -> WL_DISCONNECTED6
14:55:17.602 -> cleared
14:55:18.250 -> starting wifi
14:55:18.250 -> wifi failed
14:55:18.250 -> 6
```

Any suggestions what the issue with the first one might be?

**Comment by nitko12** [comment]
This indicated there are no SSID-s available, could be a dead esp32 wifi chip or similiar.

Try reaching out to tech-support@e-radionica.com 

Btw please link this issue there and explain a bit more what happened, 
you will get a replacement Inkpalte in case it is indeed a faulty esp32.

Thanks for reaching out :)
