### ISSUE TITLE
Add Ability to Turn Off Blue Power LED

### ISSUE THREAD

**Issue by leoherzog** [e-radionicacom/Inkplate-Arduino-library#220]
Please add a `Inkplate.setPowerLED()` function so we can reduce battery consumption.

**Comment by rsoric** [comment]
Hi @leoherzog 

Some Inkplate models have a switch on the back specifically for this, it should be labeled as "POWER LED" and it allows for the power LED to be turned off. We don't have connections from the microcontroller to that switch so we can't implement it in software. Check the schematic for your particular Inkplate if you wish to add a MOSFET connected to a GPIO pin to turn this on or off. I can help you with any info you might need to do this.
