### ISSUE TITLE
Possible mistake in Inkplate.cpp

### ISSUE THREAD

**Issue by turgu1** [e-radionicacom/Inkplate-Arduino-library#47]
Hello all,

I found what I think to be a little mistake in the Inkplate::partialUpdate() function. The beginning of it:

```C++
void Inkplate::partialUpdate()
{
    if (getDisplayMode() == 1)
        return;
    if (_blockPartial == 1)
        display1b();

    uint16_t _pos = 59999;
```

should be:

```C++
void Inkplate::partialUpdate()
{
    if (getDisplayMode() == 1)
        return;
    if (_blockPartial == 1) {
        display1b();
        return;
    }

    uint16_t _pos = 59999;
```

There is no need to run the rest of the partialUpdate() function when the code is forcing (_blockPartial == 1) the use of the display1b() function. It doesn't hurt the end result but is not useful.

Cheers!!!
Guy

**Comment by BornaBiro** [comment]
I really don't know how we missed return after 1 bit mode forced refresh, but return definitely should be after full screen update and it should not write to screen anything else after.
If this is done repeatedly it could cause burn in.
We will fix this ASAP!

Thanks for the report!

**Comment by turgu1** [comment]
Hello Borna,
Can we exchange some e-mail off github. I've some questions for you in regard of the refresh algorithm.
Thanks
Guy: turgu666@gmail.com

**Comment by BornaBiro** [comment]
No problem.
I send you an e-mail. :)

**Comment by BornaBiro** [comment]
Bug is fixed in https://github.com/e-radionicacom/Inkplate-Arduino-library/commit/067fb7c77c928ba837d1e7956a83bb4c6565dfe6
