### ISSUE TITLE
potenciometer , rotor

### ISSUE THREAD

**Issue by moje01konto** [e-radionicacom/Inkplate-Arduino-library#55]
In my opinion rotot setting are better than click keys.
for example rotor input text is better than arrows and enter.

Meybe add 2 button (home and back) == 5 keys in project
and one rotor.

**Comment by davidzovko** [comment]
Thanks for your recommendation - it has been passed onto the hardware team. We will discuss implementing it, but I think the mechanical design might be an issue.
