### ISSUE TITLE
ReadBattery function

### ISSUE THREAD

**Issue by ifadiga** [e-radionicacom/Inkplate-Arduino-library#58]
Add code for function readBattery to make it dependent on board selection.
In readBattery function for the old Inkplate6 code is the same as now.
For all new Inkplate boards, swap the state of MCP pin in readBattery function, to make the MCP pin be LOW all the time except when measuring battery voltage.

**Comment by nitko12** [comment]
Done.

https://github.com/e-radionicacom/Inkplate-Arduino-library/commit/2ace0248a5399d4fc6f28e31d7d60d24c011a449
