### ISSUE TITLE
How to tell which touchpad caused wake-up from deep sleep?

### ISSUE THREAD

**Issue by hoytech** [e-radionicacom/Inkplate-Arduino-library#66]
Hi!

The Inkplate_Wake_up_on_touchpads.ino example shows how to wake-up when button 1 is pressed. I managed to get it to wakeup when any of the 3 pads are pressed, but I can't figure out how to tell *which* one of the pads triggered the wake-up.

Any help appreciated, thanks in advance!

**Comment by davidzovko** [comment]
Hello,

first thing that Inkplate does after waking up should be checking which pin is pressed. At that moment, the finger is still on the pads and you should be able to get that reading.

**Comment by hoytech** [comment]
Good idea, will try it thanks!
