### ISSUE TITLE
Inkplate_basic_gray:32:10: error: multi-line comment [-Werror=comment]

### ISSUE THREAD

**Issue by as17** [e-radionicacom/Inkplate-Arduino-library#69]
the Inkplate_basic_gray has the following line (line 31-33):

`#define DELAY_MS                                                                                                       \`
` 5000 //Delay in milliseconds between screen refresh. Refreshing e-paper screens more often than 5s is not recommended \`
`                //Want to refresh faster? Use partial update! Find example in "Inkplate-basic_partial_update"`

The backslash does not work it throws an error. Changing this to
`#define DELAY_MS 5000 //Delay in milliseconds between screen refresh. Refreshing e-paper screens more often than 5s is not recommended Want to refresh faster? Use partial update! Find example in "Inkplate-basic_partial_update"`
makes this error disappear

**Comment by nitko12** [comment]
How did you open and save the file, some autoformatters seem to break multiline precompiler directives?

**Comment by as17** [comment]
Hi,
No auto formatting -as I know. Used the Arduino IDE.

But opening the original file in git with the git viewer:

There is this strange new line as well…..
A
