### ISSUE TITLE
several errors during compilation

### ISSUE THREAD

**Issue by as17** [e-radionicacom/Inkplate-Arduino-library#70]
1. I can compile and submit to the Inkplate the example **Inkplate_basic_BW** without any problems.
2. I **cannot** compile many other examples. E.g for **Inkplate_basic_gray** it throws the following error:
`/Users/andreas/Documents/Arduino/libraries/InkplateLibrary/src/boards/Inkplate6.cpp: In member function 'void Inkplate::display3b()':
/Users/andreas/Documents/Arduino/libraries/InkplateLibrary/src/boards/Inkplate6.cpp:262:82: error: operation on 'dp' may be undefined [-Werror=sequence-point]
             hscan_start((GLUT2[k * 256 + (*(--dp))] | GLUT[k * 256 + (*(--dp))]));
                                                                                  ^
/Users/andreas/Documents/Arduino/libraries/InkplateLibrary/src/boards/Inkplate6.cpp:263:90: error: operation on 'dp' may be undefined [-Werror=sequence-point]
             GPIO.out_w1ts = (GLUT2[k * 256 + (*(--dp))] | GLUT[k * 256 + (*(--dp))]) | CL;
                                                                                          ^
/Users/andreas/Documents/Arduino/libraries/InkplateLibrary/src/boards/Inkplate6.cpp:268:94: error: operation on 'dp' may be undefined [-Werror=sequence-point]
                 GPIO.out_w1ts = (GLUT2[k * 256 + (*(--dp))] | GLUT[k * 256 + (*(--dp))]) | CL;
                                                                                              ^
/Users/andreas/Documents/Arduino/libraries/InkplateLibrary/src/boards/Inkplate6.cpp:270:94: error: operation on 'dp' may be undefined [-Werror=sequence-point]
                 GPIO.out_w1ts = (GLUT2[k * 256 + (*(--dp))] | GLUT[k * 256 + (*(--dp))]) | CL;
                                                                                              ^
cc1plus: some warnings being treated as errors
Mehrere Bibliotheken wurden für "WiFiClient.h" gefunden
 Benutzt: /Users/andreas/Library/Arduino15/packages/Croduino_Boards/hardware/Inkplate/1.0.1/libraries/WiFi
 Nicht benutzt: /Applications/Arduino.app/Contents/Java/libraries/WiFi
exit status 1
Fehler beim Kompilieren für das Board Inkplate 6 (ESP32).`

3. Inkplate_Maze_Generator throws this error:
`/Users/andreas/Documents/Arduino/libraries/InkplateLibrary/src/boards/Inkplate6.cpp: In member function 'void Inkplate::display3b()':
/Users/andreas/Documents/Arduino/libraries/InkplateLibrary/src/boards/Inkplate6.cpp:262:82: error: operation on 'dp' may be undefined [-Werror=sequence-point]
             hscan_start((GLUT2[k * 256 + (*(--dp))] | GLUT[k * 256 + (*(--dp))]));
                                                                                  ^
/Users/andreas/Documents/Arduino/libraries/InkplateLibrary/src/boards/Inkplate6.cpp:263:90: error: operation on 'dp' may be undefined [-Werror=sequence-point]
             GPIO.out_w1ts = (GLUT2[k * 256 + (*(--dp))] | GLUT[k * 256 + (*(--dp))]) | CL;
                                                                                          ^
/Users/andreas/Documents/Arduino/libraries/InkplateLibrary/src/boards/Inkplate6.cpp:268:94: error: operation on 'dp' may be undefined [-Werror=sequence-point]
                 GPIO.out_w1ts = (GLUT2[k * 256 + (*(--dp))] | GLUT[k * 256 + (*(--dp))]) | CL;
                                                                                              ^
/Users/andreas/Documents/Arduino/libraries/InkplateLibrary/src/boards/Inkplate6.cpp:270:94: error: operation on 'dp' may be undefined [-Werror=sequence-point]
                 GPIO.out_w1ts = (GLUT2[k * 256 + (*(--dp))] | GLUT[k * 256 + (*(--dp))]) | CL;
                                                                                              ^
cc1plus: some warnings being treated as errors
Mehrere Bibliotheken wurden für "WiFiClient.h" gefunden
 Benutzt: /Users/andreas/Library/Arduino15/packages/Croduino_Boards/hardware/Inkplate/1.0.1/libraries/WiFi
 Nicht benutzt: /Applications/Arduino.app/Contents/Java/libraries/WiFi
exit status 1
Fehler beim Kompilieren für das Board Inkplate 6 (ESP32).?` as well
4. the Game_Of_Life_by_claud9999 returns an other error:
`/Users/andreas/Documents/Arduino/libraries/InkplateLibrary/examples/Inkplate_6/Community_Contributions/Game_Of_Life_by_claud9999/Game_Of_Life_by_claud9999/Game_Of_Life_by_claud9999.ino: In function 'void loop()':
Game_Of_Life_by_claud9999:126:32: error: suggest parentheses around '&&' within '||' [-Werror=parentheses]
             if (cell_next != 0 && cell_curr == 0 || cell_next == 0 && cell_curr != 0)
                                ^
cc1plus: some warnings being treated as errors
Mehrere Bibliotheken wurden für "WiFiClient.h" gefunden
 Benutzt: /Users/andreas/Library/Arduino15/packages/Croduino_Boards/hardware/Inkplate/1.0.1/libraries/WiFi
 Nicht benutzt: /Applications/Arduino.app/Contents/Java/libraries/WiFi
exit status 1
suggest parentheses around '&&' within '||' [-Werror=parentheses]`

As if Arduino does not understand the code correctly.......
Any Idea?

Setup:
Arduino IDE v 1.8.13; python 2.7.16; python3 3.9.2; MacMini M1 (2020); BigSur 11.2.2; Inkplate6; installed Inkplate board definition and example files today.

**Comment by nitko12** [comment]
Could you try with the new code on master?

It was indeed a warning that your IDE probably considered as an error.

**Comment by as17** [comment]
Hi

I tried the following examples (Inkplate6) using the git library https://github.com/e-radionicacom/Inkplate-Arduino-library.git <https://github.com/e-radionicacom/Inkplate-Arduino-library.git> downloaded today:
(I am using the native Arduino IDE - no other tool that does line breaks!)

Hope this helps a little……

MySetup: BigSur 11.2.3, Xcode command line tool installed, Arduino 1.8.13

You did what I always wanted to do: a nice clean eInkPaper monitor!!!!! Cool stuff!

Andreas.



Inkplate_basic_gray:
ERROR
error with line#31 (multiline comment); after correcting - NO problem anymore
WARNING
/Users/andreas/Documents/Arduino/libraries/InkplateLibrary/src/include/ShapesPolygon.cpp: In member function 'void Shapes::fillPolygon(int*, int*, int, int)':
/Users/andreas/Documents/Arduino/libraries/InkplateLibrary/src/include/ShapesPolygon.cpp:239:45: warning: 'y2' may be used uninitialized in this function [-Wmaybe-uninitialized]
             storeEdgeInTable(x1, y1, x2, y2);
                                             ^
/Users/andreas/Documents/Arduino/libraries/InkplateLibrary/src/include/ShapesPolygon.cpp:239:45: warning: 'x2' may be used uninitialized in this function [-Wmaybe-uninitialized]

=> WORKS (after correcting error)

Inkplate_basic_BW:
ERROR
error with line#26 (multiline comment); after correcting - NO problem anymor
WARNING
—> WARNING(Inkplate_basic_gray)

=> WORKS (after correcting error)

Inkplate_basic_partial_update:
ERROR: none
WARNING
—> WARNING(Inkplate_basic_gray)

=> WORKS

Inkplate_basic_partial_update:
ERROR: none
WARNING
—> WARNING(Inkplate_basic_gray)

=> WORKS

Inkplate_Battery_Voltage_And_Temperature:
ERROR: none
WARNING
—> WARNING(Inkplate_basic_gray)

=> WORKS

Game_Of_Life_by_claud9999:
ERROR: 
/Users/andreas/Documents/Arduino/libraries/InkplateLibrary/examples/Inkplate_6/Community_Contributions/Game_Of_Life_by_claud9999/Game_Of_Life_by_claud9999/Game_Of_Life_by_claud9999.ino: In function 'void loop()':
Game_Of_Life_by_claud9999:126:32: error: suggest parentheses around '&&' within '||' [-Werror=parentheses]
             if (cell_next != 0 && cell_curr == 0 || cell_next == 0 && cell_curr != 0)
                                ^
cc1plus: some warnings being treated as errors
Mehrere Bibliotheken wurden für "WiFiClient.h" gefunden
 Benutzt: /Users/andreas/Library/Arduino15/packages/Croduino_Boards/hardware/Inkplate/1.0.1/libraries/WiFi
 Nicht benutzt: /Applications/Arduino.app/Contents/Java/libraries/WiFi


exit status 1
suggest parentheses around '&&' within '||' [-Werror=parentheses]
WARNING


=> DOES NOT WORK

Inkplate_Mandelbrot_set:
	
ERROR: none
WARNING
—> WARNING(Inkplate_basic_gray)

=> WORKS


Inkplate_Maze_Generator
	
ERROR: none
WARNING
—> WARNING(Inkplate_basic_gray)

=> WORKS

Inkplate_Maze_Generator
	
ERROR: none
WARNING
—> WARNING(Inkplate_basic_gray)

=> WORKS


OpenWeather_station_example
	
ERROR: 
In file included from /var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_859776/OpenWeather_station_example.ino:60:0:
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_868968/sketch/Fonts/Roboto_Light_120.h:199:93: error: narrowing conversion of '-114' from 'int' to 'uint8_t {aka unsigned char}' inside { } [-Wnarrowing]
     (uint8_t *)Roboto_Light_120Bitmaps, (GFXglyph *)Roboto_Light_120Glyphs, 0x20, 0x7E, -114};
                                                                                             ^
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_859776/OpenWeather_station_example.ino: In function 'void GetCurrentWeather()':
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_859776/OpenWeather_station_example.ino:151:78: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
     OWOC.parseWeather(ONECALLKEY, NULL, myLatitude, myLongitude, metric, NULL);
                                                                              ^
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_859776/OpenWeather_station_example.ino:151:78: warning: passing NULL to non-pointer argument 6 of 'int OpenWeatherOneCall::parseWeather(char*, char*, float, float, bool, int)' [-Wconversion-null]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_859776/OpenWeather_station_example.ino: In function 'void drawForecast()':
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_859776/OpenWeather_station_example.ino:346:9: warning: unused variable 'xOffset' [-Wunused-variable]
     int xOffset = 10;
         ^
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_859776/OpenWeather_station_example.ino: In function 'void drawTime()':
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_859776/OpenWeather_station_example.ino:387:9: warning: unused variable 'textWidth' [-Wunused-variable]
     int textWidth;
         ^
Mehrere Bibliotheken wurden für "WiFi.h" gefunden
 Benutzt: /Users/andreas/Library/Arduino15/packages/Croduino_Boards/hardware/Inkplate/1.0.1/libraries/WiFi
 Nicht benutzt: /Applications/Arduino.app/Contents/Java/libraries/WiFi



exit status 1
Fehler beim Kompilieren für das Board Inkplate 6 (ESP32).


=> DOES NOT WORK


Inkplate_SD_pictures
ERROR: none
WARNING
—> WARNING(Inkplate_basic_gray)

=> seems to WORK (did not wait until it displayed. Just waited 3 minutes)

Inkplate_Touchpads
ERROR: none
WARNING
—> WARNING(Inkplate_basic_gray)

=> WORKS (of course no touch functionality)

Inkplate_Web_Pictures
ERROR: none
WARNING
—> WARNING(Inkplate_basic_gray)

=> WORKS

Crypto_tracker_example
ERROR/WARNING:
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_346362/Crypto_tracker_example.ino:33:14: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 char *ssid = "ssidofmynetwork";
              ^
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_346362/Crypto_tracker_example.ino:34:14: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 char *pass = „pwofmynetwork";
              ^
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_346362/Crypto_tracker_example.ino:40:18: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 char *currency = "bitcoin";
                  ^
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_346362/Crypto_tracker_example.ino:41:22: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 char *currencyAbbr = "BTC";
                      ^
In file included from /var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_346362/Crypto_tracker_example.ino:55:0:
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '-131' from 'int' to 'int8_t {aka signed char}' inside { } [-Wnarrowing]
 };
 ^
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '-130' from 'int' to 'int8_t {aka signed char}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '-130' from 'int' to 'int8_t {aka signed char}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '66015' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '66218' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '66837' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '67842' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '68007' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '69287' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '69986' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '70833' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '71860' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '72887' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '73328' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '74043' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '74657' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '75364' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '76129' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '77309' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '78064' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '79135' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '79847' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '80789' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:197:1: error: narrowing conversion of '80941' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_build_308732/sketch/Fonts/Roboto_Light_160.h:199:92: error: narrowing conversion of '-67' from 'int' to 'uint8_t {aka unsigned char}' inside { } [-Wnarrowing]
     (uint8_t *)Roboto_Light_160Bitmaps, (GFXglyph *)Roboto_Light_160Glyphs, 0x20, 0x7E, -67};
                                                                                            ^
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_346362/Crypto_tracker_example.ino:104:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 };
 ^
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_346362/Crypto_tracker_example.ino:104:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_346362/Crypto_tracker_example.ino:104:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_346362/Crypto_tracker_example.ino:104:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_346362/Crypto_tracker_example.ino:104:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_346362/Crypto_tracker_example.ino:104:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_346362/Crypto_tracker_example.ino:104:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_346362/Crypto_tracker_example.ino:104:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_346362/Crypto_tracker_example.ino:104:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_346362/Crypto_tracker_example.ino:104:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_346362/Crypto_tracker_example.ino:104:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_346362/Crypto_tracker_example.ino:104:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_346362/Crypto_tracker_example.ino:120:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 };
 ^
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_346362/Crypto_tracker_example.ino:120:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
/var/folders/k_/76ykyjh54ps54wd787xbtcww0000gn/T/arduino_modified_sketch_346362/Crypto_tracker_example.ino:120:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
Mehrere Bibliotheken wurden für "WiFiClient.h" gefunden
 Benutzt: /Users/andreas/Library/Arduino15/packages/Croduino_Boards/hardware/Inkplate/1.0.1/libraries/WiFi
 Nicht benutzt: /Applications/Arduino.app/Contents/Java/libraries/WiFi

=> does NOT WORK


Inkplate_VariPass_Graphs:
	
ERROR: none
WARNING
—> WARNING(Inkplate_basic_gray)

=> WORKS

**Comment by nitko12** [comment]
Hi, 

multiline comments have been removed, I'll try removing others soon.

You could try changing compile warnings to none in Arduino prefrences for now, but the fix is coming for -Wall too.

I've opened an issue on the site where fonts we're generated, but will replace them with warning free ones soon too.

**Comment by as17** [comment]
Thanks!
I can work with the library as is now. The functionalities I need work….
CU

**Comment by nitko12** [comment]
In the latest push to dev branch I've removed all warnings I've managed to find, in the next release it should all work even with all warning set in the IDE :) 

I'll close this now, feel free to reopen if you find anything weird again :D
