### ISSUE TITLE
Long SSIDs do not work

### ISSUE THREAD

**Issue by mh-g** [e-radionicacom/Inkplate-Arduino-library#72]
The Inkplate Arduino library cannot handle 32 characters long SSIDs. 31 characters do work.

I just moved all devices to the new WiFi, Inkplate being the last ... Gniiiii ...

**Comment by davidzovko** [comment]
Unfortunately, that's Arduino core limitation, not the Inkplate: https://github.com/espressif/arduino-esp32/issues/3218
