### ISSUE TITLE
Uninitialized variable in Inkplate::partialUpdate() of the Inkplate-6PLUS driver

### ISSUE THREAD

**Issue by turgu1** [e-radionicacom/Inkplate-Arduino-library#77]
Hello all!

Variable named _send is being used in the inner loop of the Inkplate::partialUpdate() method, but it was not initialized.

Cheers!
Guy

**Comment by PericR** [comment]
Thanks Guy, I removed it since its not used anymore.
https://github.com/e-radionicacom/Inkplate-Arduino-library/commit/d822a6ecba56755c732fb5b89ce26fc45fb3caa5
