### ISSUE TITLE
should not use ARDUINO_ESP32_DEV for Inkplate6

### ISSUE THREAD

**Issue by vvuk** [e-radionicacom/Inkplate-Arduino-library#86]
This library uses `ARDUINO_ESP32_DEV` for Inkplate6, instead of an `ARDUINO_INKPLATE6` definition.  The `esp32dev` board seems to be a good base for inkplate for, e.g. platformio, but because this define is also used for inkplate6, it's impossible to easily use an inkplate10 without defining a custom board.

Board definitions should really create and use an `INKPLATE6` define.

**Comment by PericR** [comment]
Hello, reason we left ARDUINO_ESP32_DEV is that we plan on making never version of Inkplate6 that will use ARDUINO_INKPLATE6. For inkplate 10 please download and install latest board definitions where you can select ARDUINO_INKPLATE10 

https://github.com/e-radionicacom/Croduino-Board-Definitions-for-Arduino-IDE
