### ISSUE TITLE
Document "wake up" button

### ISSUE THREAD

**Issue by hoytech** [e-radionicacom/Inkplate-Arduino-library#87]
I just got my Inkplate 10, and noticed there's now a "wake-up" button that wasn't present on Inkplate 6. I can't find any documentation on this. I tried the "wake up on touchpads" sample and pressing the button didn't wake it up.

How does it work, and are there any code examples?

Thanks!

**Comment by nitko12** [comment]
Hi,

we'll add it in the next release in the wake up on touchpads example, here is the draft:

https://github.com/e-radionicacom/Inkplate-Arduino-library/commit/a66425ab6aa710bc6ebc58fd0e90cc761be16c8b

I'll close this now, feel free to reopen if you need anything :)

**Comment by hoytech** [comment]
Thanks!
